# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2020-04-03 08:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bookList',
            fields=[
                ('id', models.IntegerField(default=0, null=True)),
                ('book_name', models.CharField(max_length=30)),
                ('book_author', models.CharField(max_length=200)),
                ('book_publisher', models.CharField(max_length=30, null=True)),
                ('book_translator', models.CharField(max_length=30)),
                ('book_page_num', models.CharField(max_length=30, null=True)),
                ('book_score', models.FloatField(null=True)),
                ('book_rating_num', models.IntegerField(null=True)),
                ('book_comm1', models.CharField(max_length=500)),
                ('book_comm2', models.CharField(max_length=500)),
                ('book_comm3', models.CharField(max_length=500)),
                ('book_comm4', models.CharField(max_length=500)),
                ('book_comm5', models.CharField(max_length=500)),
                ('book_stars5', models.FloatField(null=True)),
                ('book_stars4', models.FloatField(null=True)),
                ('book_stars3', models.FloatField(null=True)),
                ('book_stars2', models.FloatField(null=True)),
                ('book_stars1', models.FloatField(null=True)),
                ('kind', models.CharField(default=0, max_length=16)),
                ('No', models.IntegerField(default=0, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DayNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=django.utils.timezone.now, verbose_name='日期')),
                ('count', models.IntegerField(default=0, verbose_name='网站访问次数')),
            ],
            options={
                'verbose_name': '网站日访问量统计',
                'verbose_name_plural': '网站日访问量统计',
            },
        ),
        migrations.CreateModel(
            name='Userip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=30, verbose_name='IP地址')),
                ('count', models.IntegerField(default=0, verbose_name='访问次数')),
            ],
            options={
                'verbose_name': '访问用户信息',
                'verbose_name_plural': '访问用户信息',
            },
        ),
        migrations.CreateModel(
            name='VisitNumber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=0, verbose_name='网站访问总次数')),
            ],
            options={
                'verbose_name': '网站访问总次数',
                'verbose_name_plural': '网站访问总次数',
            },
        ),
    ]
