# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-10 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0002_auto_20200309_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='No',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='book_rating_num',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='kind',
            field=models.CharField(default=0, max_length=16),
        ),
    ]
