# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2020-03-10 09:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_web', '0003_auto_20200310_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booklist',
            name='No',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='booklist',
            name='id',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
